name: file_saver_example
description: Demonstrates how to use the file_saver plugin.

publish_to: "none"

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  excel:
  file_picker: ^5.5.0
  file_saver:
    path: ../
  cupertino_icons: ^1.0.4
  permission_handler: 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
