name: file_saver_example
description: Demonstrates how to use the file_saver plugin.

publish_to: "none"

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  excel: ^4.0.6
  file_picker: ^10.2.0
  file_saver:
    path: ../
  cupertino_icons: ^1.0.8
  permission_handler: ^12.0.0+1 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
